name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - src/slides/**/*.md
      - "**.astro"
      - "**.css"
      - bun.lock
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - src/slides/**/*.md
      - "**.astro"
      - "**.css"
      - bun.lock
      - .github/workflows/ci.yml

permissions: {}

jobs:
  astro-check:
    name: 🚀 Astro Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@c9c3ab35f0a7966a0858c71067b71248e5873e6c # v0.11.1

      - name: 🚀 Astro check
        run: bun run check:astro

  biome-check:
    name: 🏞️ Biome Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with Cache
        uses: 5ouma/utils/setup-bun-with-cache@c9c3ab35f0a7966a0858c71067b71248e5873e6c # v0.11.1

      - name: 🏞️ Biome check
        run: bun run check:biome

  textlint:
    name: ✏️ textlint
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@c9c3ab35f0a7966a0858c71067b71248e5873e6c # v0.11.1

      - name: ✏️ Run textlint
        run: bun run check:textlint

  build-check:
    name: 🛠️ Build Check
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@c9c3ab35f0a7966a0858c71067b71248e5873e6c # v0.11.1

      - name: 🛠️ Build check
        run: bun run build
