name: 🎽 CI

on:
  push:
    branches:
      - main
    paths:
      - src/slides/**/*.md
      - "**.astro"
      - "**.css"
      - bun.lock
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - src/slides/**/*.md
      - "**.astro"
      - "**.css"
      - bun.lock
      - .github/workflows/ci.yml

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  astro-check:
    name: 🚀 Astro Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@bef1602ec7e587127ade273d6490f359c6fea95b # v0.12.3

      - name: 🚀 Astro check
        run: bun run check:astro

  biome-check:
    name: 🏞️ Biome Check
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with Cache
        uses: 5ouma/utils/setup-bun-with-cache@bef1602ec7e587127ade273d6490f359c6fea95b # v0.12.3

      - name: 🏞️ Biome check
        run: bun run check:biome

  textlint:
    name: ✏️ textlint
    runs-on: Ubuntu-Slim
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@bef1602ec7e587127ade273d6490f359c6fea95b # v0.12.3

      - name: ✏️ Run textlint
        run: bun run check:textlint

  build-check:
    name: 🛠️ Build Check
    runs-on: Ubuntu-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@bef1602ec7e587127ade273d6490f359c6fea95b # v0.12.3

      - name: 🛠️ Build check
        run: bun run build
