name: 🚀 Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - themes/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    name: 🚀 Deploy
    permissions:
      contents: read
      deployments: write
    runs-on: macOS-Latest
    timeout-minutes: 1

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@311e27d5690f66c3dcb1826578cadecb13948212 # v0.7.0

      - name: 🛠️ Build
        run: bun run build

      - name: 🖼️ Replace OGP path
        run: |
          while read -r file; do
            dir="$(echo "$file" | cut -d '/' -f 2- | xargs dirname)"
            sed -i '' "s?\"index.png\"?\"$url/$dir/index.png\"?g" "$file"
          done < <(find dist -name '*.html')
        env:
          url: ${{ vars.HOST_URL }}

      - name: ⛅️ Deploy to production
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          command: deploy --name=${{ github.event.repository.name }} --compatibility-date="$(date +%Y-%m-%d)" --assets=./dist
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
