name: 🚀 Deploy

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - themes/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    name: 🚀 Deploy
    permissions:
      contents: read
      deployments: write
    runs-on: macOS-Latest
    environment:
      name: Deploy
      deployment: false
    timeout-minutes: 2

    steps:
      - name: 🚚 Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🍞 Set up Bun with cache
        uses: 5ouma/utils/setup-bun-with-cache@89264fffe82e991f0045e4a1b80d243de3011934 # v0.9.5

      - name: 🛠️ Build
        run: bun run build

      - name: 🖼️ Replace OGP path
        run: |
          while read -r file; do
            dir="$(echo "$file" | cut -d '/' -f 2- | xargs dirname)"
            sed -i '' "s?\"index.png\"?\"$url/$dir/index.png\"?g" "$file"
          done < <(find dist -name '*.html')
        env:
          url: ${{ vars.HOST_URL }}

      - name: ⛅️ Deploy to production
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          command: deploy --name=${{ github.event.repository.name }} --compatibility-date="$(date +%Y-%m-%d)" --assets=./dist
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
